CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "lastname" varchar(20) NOT NULL,
  "email" varchar(35) UNIQUE NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "role" int NOT NULL
);

CREATE TABLE "course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) UNIQUE NOT NULL,
  "description" varchar NOT NULL,
  "level" int
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) UNIQUE NOT NULL,
  "url" varchar UNIQUE NOT NULL,
  "category" int NOT NULL,
  "course" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users" int NOT NULL,
  "course" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role") REFERENCES "roles" ("id");

ALTER TABLE "course" ADD FOREIGN KEY ("level") REFERENCES "levels" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("category") REFERENCES "categories" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("course") REFERENCES "course" ("id");

ALTER TABLE "teachers" ADD FOREIGN KEY ("users") REFERENCES "users" ("id");

ALTER TABLE "teachers" ADD FOREIGN KEY ("course") REFERENCES "course" ("id");

INSERT INTO categories (category) VALUES ('Front-End'), ('Back-end');

INSERT INTO levels (level) VALUES ('Beginner'), ('intermediate'), ('advanced');

INSERT INTO roles (role) VALUES ('Student'), ('Teacher'), ('Admin');

INSERT INTO users (name, lastname, email, password, age, role) VALUES 
('Luis', 'Garcia', 'luis.garcia@gmail.com', '123456', 36, 1),
('Kim', 'Reyes', 'kim.reyes@gmail.com', '654321', 28, 1),
('Carlos', 'Zeledon', 'carlos.zeledons@gmail.com', 'mnbv123', 21, 1),
('Brenda', 'Gonzalez', 'brenda.gonzalez@gmail.com', 'bren123', 27, 2),
('Ian', 'Rosas', 'Ian.rosas@gmail.com', 'ian321', 32, 2),
('Andres', 'Mendoza', 'andres.mendoza@gmail.com', 'And123456', 23, 2);

INSERT INTO course (title, description, level) VALUES
('Fundamentos', 'Introduccion a los fundamentos de desarrollo web', 1),
('ReactJS', 'Cree componentes encapsulados que gestionen su propio estado y cree interfaces de usuario complejas', 2),
('NodeJS', 'Manejo de Back-end y creacion de APIs', 3);

INSERT INTO course_videos (title, url, category, course) VALUES
('Introduccion Fundamentos', 'url1', 1, 1),
('Html, CSS, JS', 'url2', 1, 1),
('React Components', 'url3', 1, 2),
('Hooks', 'url4', 1, 2),
('Sql', 'url5', 2, 3);

INSERT INTO teachers (users, course) VALUES
(4, 1),
(6, 2),
(5, 3);